# Wallet Tracker Configuration

# Global settings
update_interval = 300         # 5 minutes
history_days = 7
wallets_file = "example-wallets.json" # Can be either XXX.json or XXX.toml

# Networks configuration
# Each network is defined by its chain ID
# RPC URLs are read from environment variables
[[networks]]
id = 1
name = "Ethereum"
rpc_url = "${ETH_RPC_URL}" # Read from .env file
native_token = { symbol = "ETH", decimals = 18 }
tokens = [
    { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", symbol = "USDC", decimals = 6 },
    # { address = "0x6B175474E89094C44Da98b954EedeAC495271d0F", symbol = "DAI", decimals = 18 },
    # { address = "0xdAC17F958D2ee523a2206206994597C13D831ec7", symbol = "USDT", decimals = 6 },
    { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", symbol = "WETH", decimals = 18 },
]

[[networks]]
id = 137
name = "Polygon"
rpc_url = "${POLYGON_RPC_URL}" # Read from .env file
native_token = { symbol = "MATIC", decimals = 18 }
tokens = [
    { address = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174", symbol = "USDC", decimals = 6 },
    # { address = "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063", symbol = "DAI", decimals = 18 },
    # { address = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F", symbol = "USDT", decimals = 6 },
    { address = "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619", symbol = "WETH", decimals = 18 },
]

[[networks]]
id = 42161
name = "Arbitrum"
rpc_url = "${ARBITRUM_RPC_URL}" # Read from .env file
native_token = { symbol = "ETH", decimals = 18 }
tokens = [
    { address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831", symbol = "USDC", decimals = 6 },
    # { address = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1", symbol = "DAI", decimals = 18 },
    # { address = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9", symbol = "USDT", decimals = 6 },
    { address = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1", symbol = "WETH", decimals = 18 },
]

[[networks]]
id = 10
name = "Optimism"
rpc_url = "${OPTIMISM_RPC_URL}" # Read from .env file
native_token = { symbol = "ETH", decimals = 18 }
tokens = [
    { address = "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85", symbol = "USDC", decimals = 6 },
    # { address = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1", symbol = "DAI", decimals = 18 },
    # { address = "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58", symbol = "USDT", decimals = 6 },
    { address = "0x4200000000000000000000000000000000000006", symbol = "WETH", decimals = 18 },
]

[[networks]]
id = 8453
name = "Base"
rpc_url = "${BASE_RPC_URL}" # Read from .env file
native_token = { symbol = "ETH", decimals = 18 }
tokens = [
    { address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", symbol = "USDC", decimals = 6 },
    # { address = "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb", symbol = "DAI", decimals = 18 },
    { address = "0x4200000000000000000000000000000000000006", symbol = "WETH", decimals = 18 },
]
